name: Vonage.Video.Beta NuGet Release
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Release Nuget
        uses: nexmo/github-actions/nuget-release@main
        env:
          PROJECT_FILE: Vonage.Video.Beta/Vonage.Video.Beta.csproj
          BRANCH: 0.x
          ORGANIZATION: Vonage
          REPO: vonage-dotnet-sdk
          TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          GITHUB_USER_NAME: NexmoDev
          GITHUB_EMAIL: 44278943+NexmoDev@users.noreply.github.com
          OUTPUT_PATH: Vonage.Video.Beta/bin/Release
      - name: Release Nuget
        uses: nexmo/github-actions/nuget-release@main
        env:
          PROJECT_FILE: Vonage.Video.Beta/Vonage.Video.Beta.csproj
          BRANCH: 0.x
          ORGANIZATION: Vonage
          REPO: vonage-dotnet-sdk
          TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          GITHUB_USER_NAME: NexmoDev
          GITHUB_EMAIL: 44278943+NexmoDev@users.noreply.github.com
          OUTPUT_PATH: Vonage.Video.Beta/bin/ReleaseSigned
          CONFIGURATION: ReleaseSigned
